name: umbra_core
description: Core library for Umbra.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies: 
  equatable: ^2.0.3
  mason: ^0.1.0-dev.20

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  path: ^1.8.1
  test: ^1.19.2
  very_good_analysis: ^2.4.0
